language: ruby
rvm:
- 1.9.3
- 2.0
- 2.1
- ruby-head
- jruby-19mode
- jruby-head
- rbx-2
matrix:
  allow_failures:
  - rvm: rbx-2
addons:
  code_climate:
    repo_token: 7ea441f6db20b42bf77b3d49f149f2fd683b58d714a1a2bc148820e963c77862
notifications:
  webhooks:
    secure: LMFRzP1FC7Djvhgevr73eEC9pfL+XHhrptSd8pMkdGmkLbrJEVVOKsEO5OgVd91Fqmy9NL7R5dZiSCR3b+8gUcjcsCT613jyV+THfYBOiYqNgilkw/LTb50TFhvxT/5pm7pQeMYQdCyreVmklqGwSXesAW2gP9KiRLE/DNAE7EE=
